<a href="https://colab.research.google.com/github/micheldc55/Deep-Learning/blob/main/PyTorch_intro_to_tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
print(torch.__version__)

1.13.1+cu116


# Tensors

## Creating tensors

Using torch.tensor() we can create a custom tensor. First we are starting with scalars, this are a particular case of the tensor class in which we have a single element in the tensor. But note that this is using the same class as for other tensors we will define.

In [ ]:
scalar = torch.tensor(7)
scalar

tensor(7)

Let's test some attributes of the element:
- .ndim returns the dimensions of the tensor
- .item() returns the element as a regular Python object

In [ ]:
scalar.ndim

0

In [ ]:
scalar.item()

7

In [ ]:
type(scalar.item())

int

Let's create a vector. The vector is also a tensor, so we use the same function torch.tensor(). Only now we have to pass a higher number of elements.

In [ ]:
vector = torch.tensor([1, 6, 7])
vector

tensor([1, 6, 7])

In [ ]:
vector.ndim

1

In [ ]:
vector.shape

torch.Size([3])

Let's create a matrix now. For this we will use the same nomenclature and the same function (torch.tensor()). But now we will wrap a set of vectors in square brackets:

In [ ]:
MATRIX = torch.tensor([[1, 2],
                       [0, 3]])

MATRIX

tensor([[1, 2],
        [0, 3]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[1]

tensor([0, 3])

In [ ]:
MATRIX.shape

torch.Size([2, 2])

Finally, the tensor is generally represented as a concatenation of matrices. For example, an image with three color channels is a tensor. In reality, everything we've seen so far is technically considered a tensor, but in practice we will see that tensors are generally used when referring to these type of data.

In [ ]:
TENSOR = torch.tensor([[[1, 2, 3],
                        [6, 7, 4],
                        [2, 5, 4]]])

TENSOR

tensor([[[1, 2, 3],
         [6, 7, 4],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [6, 7, 4],
        [2, 5, 4]])

# Creating random tensors

Now we want to create tensors with content, to remove the fact of having to create them by hand. There are a few ways of creating of our own tensors for quickness of use.

In [ ]:
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.6076, 0.0082, 0.8854, 0.5582],
        [0.9850, 0.5333, 0.4121, 0.4578],
        [0.6137, 0.5761, 0.5278, 0.2832]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

Let's create a random tensor that would have a similar size to an image. This is similar to what we do in Deep Learning.

In [ ]:
simil_image_tensor = torch.rand(size=(3, 224, 224))
simil_image_tensor.ndim

3

In [ ]:
simil_image_tensor.shape

torch.Size([224, 224, 3])

Now we want to create a tensor that contains all zeros or all ones. This is useful if we want to build a mask for an image.

In [ ]:
zeros = torch.zeros(3, 4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

We can also build a tensor with all ones:

In [ ]:
ones = torch.ones(3, 4)
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

Let's check the data type for each tensor we created. Since we haven't specified the tensor data type, PyTorch by default creates them with the data type torch.float32, as seen below.

In [ ]:
ones.dtype, random_tensor.dtype, ones.dtype

(torch.float32, torch.float32, torch.float32)

## Creating a range of tensors and tensors-like

In [ ]:
# If you use torch.range(xo, n) a warning will be raised
# this is solved with arange(xo, n + 1)

one_to_ten = torch.arange(1, 11)

In [ ]:
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Data Types

Tensors have a few parameters upon creation which are important to know. We will rarely be creating tensors from scratch, but they are important to know either way.

When you create a tensor, by default it will be created with the torch.float32 data type. If you pass dtype=None, the tensor will still be created with the torch.float32 data type if possible.

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0])
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)
float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], 
                               dtype=torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
float_16_tensor.dtype

torch.float16

Why would we change one or the other? The key is precision versus computation times. The tensor of dtype float16 is faster to compute, but less precise (it stores less decimals), while float64 stores more data, but it takes much more to compute.

Other important parameters are:
- device
- requires_grad

In [ ]:
float_tensor = torch.tensor([3.0, 6.0, 9.0], 
                            dtype=None, 
                            device=None, 
                            requires_grad=False)
float_tensor

Why is device, shape and datatypes important? Because they are the 3 main culprits for errors in PyTorch:
- Tensors don't have coherent data types
- Tensors are not of coherent shapes
- Tensors are not stored in the same device

## Tensor multiplication

Tensors can be multiplied easily:

In [ ]:
tensor1 = torch.rand(3, 3)
tensor2 = torch.rand(3, 3)

In [ ]:
tensor1 * tensor2

tensor([[0.5556, 0.3155, 0.0470],
        [0.1373, 0.0966, 0.1712],
        [0.2430, 0.0584, 0.6302]])

What happens if we multiply tensors of different dtypes? What happend to the dtype? If we multiply a float32 by a float 16:

In [ ]:
float_32_tensor = torch.rand(5, 5)
float_16_tensor = torch.rand(5, 5, dtype=torch.float16)

In [ ]:
prod = float_32_tensor * float_16_tensor
prod

tensor([[1.7616e-01, 1.6426e-01, 3.2708e-02, 7.4202e-04, 5.4658e-02],
        [1.5634e-01, 1.1827e-01, 3.8503e-01, 7.6887e-01, 2.2663e-01],
        [7.4207e-02, 2.0118e-02, 3.3877e-01, 7.2719e-02, 4.5845e-01],
        [1.7734e-01, 5.4055e-01, 2.7984e-01, 3.3637e-01, 3.3507e-01],
        [7.6915e-01, 1.1304e-01, 1.0106e-01, 5.9281e-02, 1.2309e-01]])

In [ ]:
prod.dtype

torch.float32

## Changing a tensor's Data Type

We use the .type() to set a new type. Bear in mind that this is not inplace.

In [ ]:
float_32_tensor.type(torch.float16)

tensor([[0.5576, 0.7988, 0.0782, 0.0025, 0.3171],
        [0.2471, 0.4883, 0.6543, 0.8223, 0.6187],
        [0.8350, 0.7490, 0.4260, 0.1053, 0.6841],
        [0.4934, 0.5679, 0.2905, 0.9897, 0.7295],
        [0.8452, 0.2776, 0.4846, 0.0615, 0.3320]], dtype=torch.float16)

In [ ]:
float_32_tensor

tensor([[0.5576, 0.7991, 0.0782, 0.0025, 0.3171],
        [0.2471, 0.4884, 0.6544, 0.8223, 0.6189],
        [0.8350, 0.7491, 0.4259, 0.1053, 0.6838],
        [0.4935, 0.5680, 0.2906, 0.9898, 0.7292],
        [0.8451, 0.2776, 0.4847, 0.0615, 0.3321]])

## Getting tensor attributes:

In [ ]:
# Tensor is not the right datatype
float_32_tensor.dtype

torch.float32

In [ ]:
# Tensor is not the right shape
float_32_tensor.shape

torch.Size([5, 5])

In [ ]:
# Tensor is not in the right device
float_32_tensor.device

device(type='cpu')

# Tensor Operations

### Multiplication by a constant

In [ ]:
tensor = torch.rand(3, 4)
tensor

tensor([[0.0167, 0.9526, 0.5477, 0.3101],
        [0.2690, 0.4646, 0.3093, 0.6332],
        [0.7334, 0.0204, 0.8231, 0.4985]])

Se puede usar * o torch.mul indistintamente

In [ ]:
tensor * 10

tensor([[0.1671, 9.5260, 5.4773, 3.1005],
        [2.6900, 4.6461, 3.0927, 6.3322],
        [7.3337, 0.2037, 8.2312, 4.9855]])

In [ ]:
torch.mul(tensor, 10)

tensor([[0.1671, 9.5260, 5.4773, 3.1005],
        [2.6900, 4.6461, 3.0927, 6.3322],
        [7.3337, 0.2037, 8.2312, 4.9855]])

### Matrix multiplication

The * operator performs element-wise multiplication, while the torch.matmul() performs matrix multiplication.

In [ ]:
one_d_tensor = torch.tensor([1, 3, 5])

print(one_d_tensor, '*', one_d_tensor)
print(one_d_tensor * one_d_tensor)

tensor([1, 3, 5]) * tensor([1, 3, 5])
tensor([ 1,  9, 25])


In [ ]:
torch.matmul(one_d_tensor, one_d_tensor)

tensor(35)

For matrix multiplication, **always use torch.matmul()**. Using the * symbol does element-wise multiplication. You can also do matrix multiplication with the "@" symbol:

In [ ]:
matrix = torch.tensor([[1, 5], [2, 2]])

In [ ]:
torch.matmul(matrix, matrix)

tensor([[11, 15],
        [ 6, 14]])

Alias for matrix multiplication with less characters

In [ ]:
torch.mm(matrix, matrix)

tensor([[11, 15],
        [ 6, 14]])

In [ ]:
matrix @ matrix

tensor([[11, 15],
        [ 6, 14]])

### Dealing with shape errors:

In [5]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]])

torch.mm(tensor_A, tensor_B)

RuntimeError: ignored

In [6]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

We need to reshape / transpose our tensors:

In [7]:
tensor_B

tensor([[ 7, 10],
        [ 8, 11],
        [ 9, 12]])

In [8]:
tensor_B.T

tensor([[ 7,  8,  9],
        [10, 11, 12]])

In [9]:
tensor_B.T.shape

torch.Size([2, 3])

In [10]:
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Now it works! In this case, it also works transposing the other matrix, but this is not always the case.

In [11]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76, 103],
        [100, 136]])

## Central tendency statistics in Tensors

In [12]:
tensor_A.min(), torch.min(tensor_A), tensor_A.max(), torch.max(tensor_B)

(tensor(1), tensor(1), tensor(6), tensor(12))

In [13]:
# Note the erros: Not the right data type!
torch.mean(tensor_A)

RuntimeError: ignored

Two ways to solve this problem:

In [14]:
torch.mean(tensor_A.type(torch.float32))

tensor(3.5000)

In [15]:
torch.mean(tensor_A, dtype=torch.float32)

tensor(3.5000)

### Finding the position of these values

The argmax or argmin returns the position of the max/min in the element.

In [16]:
tensor_A

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [17]:
tensor_A.argmin()

tensor(0)

In [18]:
tensor_A.argmax()

tensor(5)

In [20]:
torch.argmax(tensor_A)

tensor(5)

## Reshaping / Viewing / Stacking / Squeezing tensors

These are a few regular operations that are widely diffused in Deep Learning.

- Reshaping: Changing the input tensor to a defined shape (size).
- View: Given a certain tensor, it returns a view of the tensor but the memory is kept the same.
- Stacking: Piling torch tensors together. For example, if we have three matrixes, one for each channel. If we stack them we get an RGB image.
- Squeeze: Removes all 1 dimensions from a tensor.
- Unsqueeze: Adds 1 dimension to the tensor passed.
- Permute: Returns a view of the input with dimensions permuted in a certain way.

In [21]:
x = torch.arange(1.0, 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [22]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

RuntimeError: ignored

This obviouslty won't work because the target shape is not coherent with the original dimension.

In [23]:
x_reshaped = x.reshape(1, 9)
x_reshaped

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [24]:
x_reshaped = x.reshape(9, 1)
x_reshaped

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [26]:
x_reshaped = x.reshape(3, 3)
x_reshaped

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

### Changing the view:

The view shares the same memory as the original input. This means that if we modify "z", these changes will apply to "x".

In [28]:
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

Changing "z" to verify that "x" changes.

In [29]:
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

### Stacking

In [31]:
torch.stack([x, x, x, x], dim=0)

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [32]:
torch.stack([x, x, x, x], dim=1)

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [33]:
torch.stack([x, x, x, x], dim=2)

IndexError: ignored

### Squeezing

Squeezing removes all the dimensions of elements in the tensor that have dim=1

Unsqueezing does the same, but it adds a dimension at the dimension = dim.

In [36]:
x_sq = torch.rand(1, 2, 3)
x_sq

tensor([[[0.5160, 0.3336, 0.9971],
         [0.6858, 0.1724, 0.4372]]])

In [38]:
x_sq.shape, torch.squeeze(x_sq).shape

(torch.Size([1, 2, 3]), torch.Size([2, 3]))

In [42]:
x_unsq = torch.rand(3)
x_unsq

tensor([0.7534, 0.9524, 0.1876])

In [44]:
torch.unsqueeze(x_unsq, 1)

tensor([[0.7534],
        [0.9524],
        [0.1876]])

In [47]:
torch.unsqueeze(x_unsq, 1).shape

torch.Size([3, 1])

In [48]:
torch.unsqueeze(x_unsq, 0)

tensor([[0.7534, 0.9524, 0.1876]])

### Permuting

Swaps the order of the different dimensions. This is better understood with an example:

In [52]:
a = torch.rand(224, 224, 3)
a.shape

torch.Size([224, 224, 3])

In [53]:
a.permute(2, 0, 1).shape

torch.Size([3, 224, 224])

In [54]:
a.shape

torch.Size([224, 224, 3])

### Selecting data from tensors:

In [56]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [57]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
x[0, 0]

tensor([1, 2, 3])

In [59]:
x[0][0]

tensor([1, 2, 3])

In [61]:
x[0][0][0]

tensor(1)

In [62]:
x[:, 1, :]

tensor([[4, 5, 6]])

## Combining PyTorch & Numpy

You can convert any numpy array to a PyTorch tensor using the torch.from_numpy().

You can also convert a tensor to a numpy array by using the torch.tensor method called .numpy().

In [66]:
array = np.arange(1.0, 8.0)

In [67]:
array

array([1., 2., 3., 4., 5., 6., 7.])

In [70]:
tensor = torch.from_numpy(array)
tensor

tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64)

Note that this has dtype=torch.float64. This is important to note, as when converting from Numpy to PyTorch, PyTorch keeps the natural Numpy data type, called float64. Instead of the default torch.float32. You can change it using:

In [71]:
tensor.type(torch.float32)

tensor([1., 2., 3., 4., 5., 6., 7.])

Converted arrays or tensors point to the same place in memory:

In [75]:
array = array + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([3., 4., 5., 6., 7., 8., 9.], dtype=torch.float64))

This doesn't apply the other way around. Tensors don't point to the same place in memory than the array used to build them.

In [76]:
tensor = tensor + 1
array, tensor

(array([3., 4., 5., 6., 7., 8., 9.]),
 tensor([ 4.,  5.,  6.,  7.,  8.,  9., 10.], dtype=torch.float64))

## Reproducibility in randomness

We want to get repeatable values from our operations. This can be done by setting the seed, similar to what we do in numpy or sklearn. Every time we run the cell below, we get a different output, so if we share code this is not optimal.

In PyTorch, this is called a random seed.

In [77]:
torch.rand(3, 3)

tensor([[0.0374, 0.6252, 0.6026],
        [0.0397, 0.9928, 0.3874],
        [0.7245, 0.1603, 0.2738]])

In [81]:
random_tensor_a = torch.rand(3, 4)
random_tensor_b = torch.rand(3, 4)

In [82]:
random_tensor_a, random_tensor_b

(tensor([[0.1290, 0.8564, 0.9728, 0.1567],
         [0.2003, 0.5835, 0.2456, 0.9156],
         [0.4967, 0.7569, 0.5343, 0.4547]]),
 tensor([[0.8131, 0.0851, 0.6867, 0.3290],
         [0.0961, 0.1383, 0.7938, 0.9698],
         [0.5888, 0.2876, 0.7103, 0.2028]]))

In [83]:
random_tensor_a == random_tensor_b

tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

We may want random experiments but reproducible. For that, we can set a random seed. The random seed works like in Numpy, so you have to call it each time you execute torch."something"

In [85]:
random_seed = 101

torch.manual_seed(random_seed)
random_tensor_c = torch.rand(3, 4)

torch.manual_seed(random_seed)
random_tensor_d = torch.rand(3, 4)

random_tensor_c == random_tensor_d

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

# The concept of running on CPU / GPU

All PyTorch objects can be run either in your computer's CPU, or in the GPU. This allows for faster computation, but you need to be explicit with it in PyTorch.

In order to check if you are running on GPU, especially if you are using NVIDIA GPUs is executing the nvidia-smi command in the command line.

This will only work if the runtime is switched to a GPU.

In [86]:
! nvidia-smi

NVIDIA-SMI has failed because it couldn't communicate with the NVIDIA driver. Make sure that the latest NVIDIA driver is installed and running.



In [87]:
torch.cuda.is_available()

False

## How to set up device-agnostic code

There is a very simple way to set up your device so that everything is agnostic to whether you have a CPU or GPU, which is basically using the torch.cuda.is_available() shown above.

Using that you can build a pipeline that is agnostic to which processing unit you have available. It goes like this:

In [88]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cpu'

Counting the number of GPUs

In [89]:
torch.cuda.device_count()

/usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:497: UserWarning: Can't initialize NVML
  warnings.warn("Can't initialize NVML")


0

In order to use the GPU, we have to put everything related to training in the GPU. Using the GPU makes computations faster, but PyTorch requires us to be explicit with where the data should be located. For training, we need both the model and the data tensors in the GPU.

In [90]:
tensor = torch.tensor([1, 2, 5], device="cpu")

You can also move the device "to" the CPU/GPU.

In [91]:
tensor_on_gpu = tensor.to(device) # this only works in GPU if it's available

### Considerations of using Numpy

There will be some times in which we want to use numpy, for example for metric calculations. The problem is that Numpy only works on you CPU, and so, if your tensors are on GPU, you need to move them to CPU for computing.

This is such a normal problem that PyTorch already has a way of dealing with this problem, called detach(), combined with numpy().

In [93]:
tensor.numpy() # If device is in GPU, this WILL NOT WORK

array([1, 2, 5])

For that, we need to detach the tensor from the GPU. We can do that with detach() and also with cpu()

In [94]:
tensor.detach().numpy()

array([1, 2, 5])

In [95]:
tensor.cpu().numpy()

array([1, 2, 5])

# Exercises

Create a random tensor with shape (7, 7).

In [98]:
tensor_1 = torch.rand(7, 7)
tensor_1

tensor([[0.8310, 0.6744, 0.0299, 0.6592, 0.3304, 0.6563, 0.5190],
        [0.0596, 0.6389, 0.3944, 0.2462, 0.1189, 0.6624, 0.2786],
        [0.0116, 0.0587, 0.4109, 0.9920, 0.0466, 0.3861, 0.1460],
        [0.5526, 0.0996, 0.7545, 0.1000, 0.2502, 0.0819, 0.5029],
        [0.2406, 0.9118, 0.9401, 0.3970, 0.5867, 0.0894, 0.8525],
        [0.1603, 0.6896, 0.9611, 0.0884, 0.4647, 0.5453, 0.5201],
        [0.9407, 0.9042, 0.5836, 0.7245, 0.6212, 0.1815, 0.0018]])

Perform a matrix multiplication on the tensor from 2 with another random tensor with shape (1, 7) (hint: you may have to transpose the second tensor).

In [101]:
tensor_2 = torch.rand(1, 7)

torch.mm(tensor_1, tensor_2.T)

tensor([[1.2034],
        [0.7906],
        [0.6977],
        [0.7396],
        [1.1912],
        [1.0834],
        [1.2750]])

Set the random seed to 0 and do exercises 2 & 3 over again.

In [102]:
torch.manual_seed(0)
tensor_1 = torch.rand(7, 7)

torch.manual_seed(0)
tensor_2 = torch.rand(1, 7)

torch.mm(tensor_1, tensor_2.T)

tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])

Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent? (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.

In [103]:
torch.cuda.manual_seed(1234)

Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this). Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).

In [104]:
device = "cuda" if torch.cuda.is_available() else "cpu"

torch.manual_seed(1234)
tensor_3 = torch.rand(2, 3)

torch.manual_seed(1234)
tensor_4 = torch.rand(2, 3)

Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).

In [107]:
output = torch.mm(tensor_3, tensor_4.T)
output

tensor([[0.2299, 0.2161],
        [0.2161, 0.6287]])

Find the maximum and minimum values of the output of 7.

In [109]:
torch.max(output), torch.min(output)

(tensor(0.6287), tensor(0.2161))

Find the maximum and minimum index values of the output of 7.

In [110]:
torch.argmax(output), torch.argmin(output)

(tensor(3), tensor(1))

Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10). Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

In [111]:
torch.manual_seed(7)
extra_tensor = torch.rand(1, 1, 1, 10)

print(extra_tensor, extra_tensor.shape)

tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]]) torch.Size([1, 1, 1, 10])


In [116]:
second_tensor = extra_tensor.squeeze()
second_tensor, second_tensor.shape

(tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]), torch.Size([10]))